// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Archives: typeof import('./components/library/Archives.vue')['default']
    ArticleCard: typeof import('./components/library/ArticleCard.vue')['default']
    Background: typeof import('./components/common/Background.vue')['default']
    Badge: typeof import('./components/wrapper/Badge.vue')['default']
    Card: typeof import('./components/common/Card.vue')['default']
    Footer: typeof import('./components/common/Footer.vue')['default']
    LibraryCount: typeof import('./components/library/LibraryCount.vue')['default']
    Link: typeof import('./components/common/Link.vue')['default']
    NaiveProvider: typeof import('./components/provider/NaiveProvider.vue')['default']
    Navbar: typeof import('./components/nav/Navbar.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    Profile: typeof import('./components/common/Profile.vue')['default']
    Recommend: typeof import('./components/library/Recommend.vue')['default']
    Shrink: typeof import('./components/wrapper/Shrink.vue')['default']
    SideNavbar: typeof import('./components/nav/SideNavbar.vue')['default']
    TabPanel: typeof import('./components/tabs/TabPanel.vue')['default']
    Tabs: typeof import('./components/tabs/Tabs.vue')['default']
    TalkBar: typeof import('./components/library/TalkBar.vue')['default']
  }
}

export { }
